# frontend/Dockerfile

# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build
# Copy sitemap into the container
#COPY sitemap.xml /app/public/   
# Production stage
FROM nginx:1.25-alpine
COPY --from=build /app/build /usr/share/nginx/html
# Copy the NGINX configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]