# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Copy only package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Start React dev server
CMD ["npm", "start"]